run:
  timeout: 5m
linters:
  disable-all: true
  enable:
  - deadcode
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck
  - gofmt
  - golint
  - gci
  - gofumpt
  - whitespace
  - godot

issues:
  include:
  - EXC0002 # disable excluding of issues about comments from golint

linters-settings:
  godot:
    # list of regexps for excluding particular comment lines from check
    exclude:
    - '^ (\d+)(\.|\)).*' # enumeration comments like // 1. or // 1)
