run:
  timeout: 5m
linters:
  disable-all: true
  enable:
  - deadcode
  - gosimple
  - govet
  - ineffassign
  - staticcheck
  - structcheck
  - typecheck
  - unused
  - varcheck
  - gofmt
  - revive
  - gci
  - gofumpt
  - whitespace
  - godot
  - unparam
  - gocritic

issues:
  include:
  - EXC0012 # disable excluding of issues about comments from revive

linters-settings:
  godot:
    # list of regexps for excluding particular comment lines from check
    exclude:
    - '^ @.*' # swaggo comments like // @title
    - '^ (\d+)(\.|\)).*' # enumeration comments like // 1. or // 1)
